# Credit Risk Prediction — TFX Machine Learning Pipeline

**Nama:** rzky0x  
**Dataset:** [Credit Risk Dataset](https://www.kaggle.com/datasets/laotse/credit-risk-dataset) (Kaggle)  
**Orchestrator:** Apache Beam (DirectRunner)  
**Pipeline Output:** `rzky0x-pipeline/`

---

## Deskripsi Proyek

Notebook ini membangun sebuah **machine learning pipeline** end-to-end menggunakan **TensorFlow Extended (TFX)** untuk memprediksi risiko kredit (loan default). Pipeline ini mencakup 9 komponen utama:

1. **ExampleGen** — Ingest data CSV
2. **StatisticsGen** — Menghasilkan statistik deskriptif
3. **SchemaGen** — Inferensi schema data
4. **ExampleValidator** — Validasi anomali data
5. **Transform** — Feature engineering
6. **Trainer** — Training model DNN
7. **Resolver** — Resolusi model terbaik sebelumnya
8. **Evaluator** — Evaluasi performa model
9. **Pusher** — Deploy model yang lolos evaluasi

## 1. Setup Environment

Install dan import library yang diperlukan untuk menjalankan TFX pipeline.

In [1]:
# Install dependencies (uncomment jika diperlukan)
# !pip install tfx==1.15.0 tensorflow==2.15.0

In [2]:
import os
import tensorflow as tf
import tensorflow_model_analysis as tfma

from tfx import v1 as tfx
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext

print(f'TensorFlow version: {tf.__version__}')
print(f'TFX version: {tfx.__version__}')

2026-06-12 21:54:44.104803: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-12 21:54:44.162086: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-06-12 21:54:44.162172: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-06-12 21:54:44.165329: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-06-12 21:54:44.177774: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-06-12 21:54:44.178763: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.api_core supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.api_core.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

2026-06-12 21:54:45.408007: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform_v1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform_v1.
  warnings.warn(message, FutureWarning)

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform_v1beta1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform_v1beta1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.resourcemanager_v3 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.resourcemanager_v3.
  warnings.warn(message, FutureWarning)

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1.schema.predict.instance_v1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1.schema.predict.instance_v1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1.schema.predict.params_v1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1.schema.predict.params_v1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1.schema.predict.prediction_v1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1.schema.predict.prediction_v1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1.schema.trainingjob.definition_v1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1.schema.trainingjob.definition_v1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1.
  warnings.warn(message, FutureWarning)
/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/google/api_core/_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1 supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1.
  warnings.warn(message, FutureWarning)

TensorFlow version: 2.15.0
TFX version: 1.15.0

## 2. Konfigurasi Pipeline

Menentukan path untuk data, pipeline artifacts, dan modul yang digunakan.

In [3]:
# Pipeline configuration
PIPELINE_NAME = 'rzky0x-pipeline'

# Paths
PIPELINE_ROOT = os.path.join(os.getcwd(), PIPELINE_NAME)
DATA_ROOT = os.path.join(os.getcwd(), 'data')
METADATA_PATH = os.path.join(PIPELINE_ROOT, 'metadata', 'metadata.db')
SERVING_MODEL_DIR = os.path.join(PIPELINE_ROOT, 'serving_model')

# Module paths
TRANSFORM_MODULE_FILE = os.path.join(os.getcwd(), 'modules', 'transform_module.py')
TRAINER_MODULE_FILE = os.path.join(os.getcwd(), 'modules', 'trainer_module.py')

print(f'Pipeline root: {PIPELINE_ROOT}')
print(f'Data root: {DATA_ROOT}')
print(f'Metadata path: {METADATA_PATH}')
print(f'Serving model dir: {SERVING_MODEL_DIR}')

Pipeline root: /home/rzkycx/so/rzky0x-pipeline
Data root: /home/rzkycx/so/data
Metadata path: /home/rzkycx/so/rzky0x-pipeline/metadata/metadata.db
Serving model dir: /home/rzkycx/so/rzky0x-pipeline/serving_model

In [4]:
# Initialize Interactive Context for running pipeline components
context = InteractiveContext(
    pipeline_name=PIPELINE_NAME,
    pipeline_root=PIPELINE_ROOT,
    metadata_connection_config=tfx.orchestration.metadata.sqlite_metadata_connection_config(METADATA_PATH)
)

## 3. Komponen 1: ExampleGen

**ExampleGen** adalah komponen pertama dalam pipeline TFX. Komponen ini bertugas untuk:
- Membaca data dari sumber (dalam kasus ini, file CSV)
- Membagi data menjadi set training dan evaluasi (default: 2/3 training, 1/3 eval)
- Mengkonversi data ke format tf.Example

Dataset yang digunakan adalah **Credit Risk Dataset** yang berisi informasi peminjam dan status pinjaman mereka.

In [5]:
# Component 1: ExampleGen - Ingest data from CSV
example_gen = tfx.components.CsvExampleGen(
    input_base=DATA_ROOT
)
context.run(example_gen)

WARNING:apache_beam.runners.interactive.interactive_environment:Dependencies required for Interactive Beam PCollection visualization are not available, please use: `pip install apache-beam[interactive]` to install necessary dependencies to enable all data visualization features.

WARNING:apache_beam.io.tfrecordio:Couldn't find python-snappy so the implementation of _TFRecordUtil._masked_crc32c is not as fast as it could be.

ExecutionResult(
    component_id: CsvExampleGen
    execution_id: 1
    outputs:
        examples: OutputChannel(artifact_type=Examples, producer_component_id=CsvExampleGen, output_key=examples, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [6]:
# Inspect ExampleGen output artifacts
artifact = example_gen.outputs['examples'].get()[0]
print(f'Split names: {artifact.split_names}')
print(f'Artifact URI: {artifact.uri}')

Split names: ["train", "eval"]
Artifact URI: /home/rzkycx/so/rzky0x-pipeline/CsvExampleGen/examples/1

## 4. Komponen 2: StatisticsGen

**StatisticsGen** menghasilkan statistik deskriptif untuk dataset, termasuk:
- Distribusi nilai untuk setiap fitur
- Statistik seperti mean, stddev, min, max
- Persentase missing values
- Top values untuk fitur kategorikal

Statistik ini digunakan oleh komponen SchemaGen dan ExampleValidator.

In [7]:
# Component 2: StatisticsGen - Generate descriptive statistics
statistics_gen = tfx.components.StatisticsGen(
    examples=example_gen.outputs['examples']
)
context.run(statistics_gen)

ExecutionResult(
    component_id: StatisticsGen
    execution_id: 2
    outputs:
        statistics: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=StatisticsGen, output_key=statistics, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [8]:
# Visualize statistics
context.show(statistics_gen.outputs['statistics'])

## 5. Komponen 3: SchemaGen

**SchemaGen** melakukan inferensi schema dari statistik data. Schema ini mendefinisikan:
- Tipe data setiap fitur (INT, FLOAT, STRING)
- Domain yang valid untuk fitur kategorikal
- Apakah fitur bersifat required atau optional
- Batasan nilai (min/max) untuk fitur numerik

Schema ini menjadi referensi untuk validasi data di komponen selanjutnya.

In [9]:
# Component 3: SchemaGen - Infer data schema
schema_gen = tfx.components.SchemaGen(
    statistics=statistics_gen.outputs['statistics']
)
context.run(schema_gen)

ExecutionResult(
    component_id: SchemaGen
    execution_id: 3
    outputs:
        schema: OutputChannel(artifact_type=Schema, producer_component_id=SchemaGen, output_key=schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [10]:
# Visualize schema
context.show(schema_gen.outputs['schema'])

,Type,Presence,Valency,Domain
Feature name,,,,
'cb_person_cred_hist_length',INT,required,,-
'cb_person_default_on_file',STRING,required,,'cb_person_default_on_file'
'loan_amnt',INT,required,,-
'loan_grade',STRING,required,,'loan_grade'
'loan_int_rate',FLOAT,required,,-
'loan_intent',STRING,required,,'loan_intent'
'loan_percent_income',FLOAT,required,,-
'loan_status',INT,required,,-
'person_age',INT,required,,-
'person_emp_length',FLOAT,required,,-
'person_home_ownership',STRING,required,,'person_home_ownership'
'person_income',INT,required,,-

                                                                                                            Values
Domain
'cb_person_default_on_file'                                                                               'N', 'Y'
'loan_grade'                                                                     'A', 'B', 'C', 'D', 'E', 'F', 'G'
'loan_intent'                'DEBTCONSOLIDATION', 'EDUCATION', 'HOMEIMPROVEMENT', 'MEDICAL', 'PERSONAL', 'VENTURE'
'person_home_ownership'                                                         'MORTGAGE', 'OTHER', 'OWN', 'RENT'

## 6. Komponen 4: ExampleValidator

**ExampleValidator** memvalidasi data terhadap schema yang telah diinferensikan. Komponen ini mendeteksi:
- Anomali data (nilai di luar domain yang diharapkan)
- Missing features yang seharusnya ada
- Data drift atau skew
- Inkonsistensi tipe data

Jika ditemukan anomali, komponen ini akan melaporkan detail masalah yang ditemukan.

In [11]:
# Component 4: ExampleValidator - Validate data against schema
example_validator = tfx.components.ExampleValidator(
    statistics=statistics_gen.outputs['statistics'],
    schema=schema_gen.outputs['schema']
)
context.run(example_validator)

ExecutionResult(
    component_id: ExampleValidator
    execution_id: 4
    outputs:
        anomalies: OutputChannel(artifact_type=ExampleAnomalies, producer_component_id=ExampleValidator, output_key=anomalies, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [12]:
# Show validation results
context.show(example_validator.outputs['anomalies'])

## 7. Komponen 5: Transform

**Transform** melakukan feature engineering pada data mentah. Komponen ini menggunakan modul `transform_module.py` yang berisi fungsi `preprocessing_fn`. Proses yang dilakukan:

- **Fitur Numerik** (`person_age`, `person_income`, `loan_amnt`, dll): Dinormalisasi menggunakan z-score scaling
- **Fitur Kategorikal** (`person_home_ownership`, `loan_intent`, `loan_grade`, dll): Di-encode menggunakan vocabulary lookup
- **Handling Missing Values**: Nilai kosong diisi dengan 0 (numerik) atau string kosong (kategorikal)

Transform menjamin konsistensi antara preprocessing saat training dan serving (menghindari training-serving skew).

In [13]:
# Component 5: Transform - Feature engineering
transform = tfx.components.Transform(
    examples=example_gen.outputs['examples'],
    schema=schema_gen.outputs['schema'],
    module_file=TRANSFORM_MODULE_FILE
)
context.run(transform)

running bdist_wheel
running build
running build_py
creating build/lib
copying trainer_module.py -> build/lib
copying transform_module.py -> build/lib
installing to /tmp/tmpr8c1aas0
running install
running install_lib
copying build/lib/trainer_module.py -> /tmp/tmpr8c1aas0/.
copying build/lib/transform_module.py -> /tmp/tmpr8c1aas0/.
running install_egg_info
running egg_info
creating tfx_user_code_Transform.egg-info
writing tfx_user_code_Transform.egg-info/PKG-INFO
writing dependency_links to tfx_user_code_Transform.egg-info/dependency_links.txt
writing top-level names to tfx_user_code_Transform.egg-info/top_level.txt
writing manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
reading manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
writing manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
Copying tfx_user_code_Transform.egg-info to /tmp/tmpr8c1aas0/./tfx_user_code_Transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3.9.egg-info
running install_scripts
creating /tmp/tmpr8c1aas0/tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/WHEEL
creating '/tmp/tmpgd6yg9kd/tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl' and adding '/tmp/tmpr8c1aas0' to it
adding 'trainer_module.py'
adding 'transform_module.py'
adding 'tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/METADATA'
adding 'tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/WHEEL'
adding 'tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/top_level.txt'
adding 'tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/RECORD'
removing /tmp/tmpr8c1aas0

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()

Processing ./rzky0x-pipeline/_wheels/tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl

Installing collected packages: tfx-user-code-transform
Successfully installed tfx-user-code-transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e

Processing ./rzky0x-pipeline/_wheels/tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl

Installing collected packages: tfx-user-code-transform
Successfully installed tfx-user-code-transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e

Processing ./rzky0x-pipeline/_wheels/tfx_user_code_transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl

Installing collected packages: tfx-user-code-transform
Successfully installed tfx-user-code-transform-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Transform/transform_graph/5/.temp_path/tftransform_tmp/ec4e63728be74c26a480906fc15d6214/assets

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Transform/transform_graph/5/.temp_path/tftransform_tmp/ec4e63728be74c26a480906fc15d6214/assets

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Transform/transform_graph/5/.temp_path/tftransform_tmp/e88a2a3895f54cfa82707074a364f399/assets

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Transform/transform_graph/5/.temp_path/tftransform_tmp/e88a2a3895f54cfa82707074a364f399/assets

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:tensorflow_text is not available.

ExecutionResult(
    component_id: Transform
    execution_id: 5
    outputs:
        transform_graph: OutputChannel(artifact_type=TransformGraph, producer_component_id=Transform, output_key=transform_graph, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        transformed_examples: OutputChannel(artifact_type=Examples, producer_component_id=Transform, output_key=transformed_examples, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        updated_analyzer_cache: OutputChannel(artifact_type=TransformCache, producer_component_id=Transform, output_key=updated_analyzer_cache, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        pre_transform_schema: OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=pre_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        pre_transform_stats: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=pre_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        post_transform_schema: OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=post_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        post_transform_stats: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=post_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        post_transform_anomalies: OutputChannel(artifact_type=ExampleAnomalies, producer_component_id=Transform, output_key=post_transform_anomalies, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [14]:
# Show transform output
transform.outputs

{'transform_graph': OutputChannel(artifact_type=TransformGraph, producer_component_id=Transform, output_key=transform_graph, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'transformed_examples': OutputChannel(artifact_type=Examples, producer_component_id=Transform, output_key=transformed_examples, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'updated_analyzer_cache': OutputChannel(artifact_type=TransformCache, producer_component_id=Transform, output_key=updated_analyzer_cache, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'pre_transform_schema': OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=pre_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'pre_transform_stats': OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=pre_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'post_transform_schema': OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=post_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'post_transform_stats': OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=post_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False),
 'post_transform_anomalies': OutputChannel(artifact_type=ExampleAnomalies, producer_component_id=Transform, output_key=post_transform_anomalies, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)}

## 8. Komponen 6: Trainer

**Trainer** melatih model menggunakan data yang telah ditransformasi. Model yang digunakan adalah **Deep Neural Network (DNN)** classifier dengan arsitektur:

- **Input Layer**: Menerima fitur numerik dan kategorikal yang telah ditransformasi
- **Hidden Layer 1**: 256 neurons, ReLU, BatchNormalization, Dropout(0.3)
- **Hidden Layer 2**: 128 neurons, ReLU, BatchNormalization, Dropout(0.3)
- **Hidden Layer 3**: 64 neurons, ReLU, BatchNormalization, Dropout(0.3)
- **Output Layer**: 1 neuron, Sigmoid (binary classification)

**Optimizer**: Adam (learning_rate=0.001)  
**Loss**: Binary Crossentropy  
**Metrics**: Binary Accuracy, AUC  
**Callback**: EarlyStopping (patience=5)

In [15]:
# Component 6: Trainer - Train the model
trainer = tfx.components.Trainer(
    module_file=TRAINER_MODULE_FILE,
    examples=transform.outputs['transformed_examples'],
    transform_graph=transform.outputs['transform_graph'],
    schema=schema_gen.outputs['schema'],
    train_args=tfx.proto.TrainArgs(num_steps=500),
    eval_args=tfx.proto.EvalArgs(num_steps=100)
)
context.run(trainer)

/home/rzkycx/so/mlops-env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

running bdist_wheel
running build
running build_py
creating build/lib
copying trainer_module.py -> build/lib
copying transform_module.py -> build/lib
installing to /tmp/tmp25c2rqux
running install
running install_lib
copying build/lib/trainer_module.py -> /tmp/tmp25c2rqux/.
copying build/lib/transform_module.py -> /tmp/tmp25c2rqux/.
running install_egg_info
running egg_info
creating tfx_user_code_Trainer.egg-info
writing tfx_user_code_Trainer.egg-info/PKG-INFO
writing dependency_links to tfx_user_code_Trainer.egg-info/dependency_links.txt
writing top-level names to tfx_user_code_Trainer.egg-info/top_level.txt
writing manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
reading manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
writing manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
Copying tfx_user_code_Trainer.egg-info to /tmp/tmp25c2rqux/./tfx_user_code_Trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3.9.egg-info
running install_scripts
creating /tmp/tmp25c2rqux/tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/WHEEL
creating '/tmp/tmp3qc7im_g/tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl' and adding '/tmp/tmp25c2rqux' to it
adding 'trainer_module.py'
adding 'transform_module.py'
adding 'tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/METADATA'
adding 'tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/WHEEL'
adding 'tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/top_level.txt'
adding 'tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e.dist-info/RECORD'
removing /tmp/tmp25c2rqux

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

Processing ./rzky0x-pipeline/_wheels/tfx_user_code_trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e-py3-none-any.whl

Installing collected packages: tfx-user-code-trainer
Successfully installed tfx-user-code-trainer-0.0+0b07e2aec0840b19eca511ad20a46586b5215684bbccd137045ba92cdafd9a3e

WARNING:tensorflow:From /home/rzkycx/so/mlops-env/lib/python3.9/site-packages/tfx_bsl/tfxio/tf_example_record.py:343: parse_example_dataset (from tensorflow.python.data.experimental.ops.parsing_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(tf.io.parse_example(...))` instead.

WARNING:tensorflow:From /home/rzkycx/so/mlops-env/lib/python3.9/site-packages/tfx_bsl/tfxio/tf_example_record.py:343: parse_example_dataset (from tensorflow.python.data.experimental.ops.parsing_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(tf.io.parse_example(...))` instead.

Model: "model"

__________________________________________________________________________________________________

 Layer (type)                Output Shape                 Param #   Connected to

==================================================================================================

 person_home_ownership_xf (  [(None, 1)]                  0         []

 InputLayer)

 loan_intent_xf (InputLayer  [(None, 1)]                  0         []

 )

 loan_grade_xf (InputLayer)  [(None, 1)]                  0         []

 cb_person_default_on_file_  [(None, 1)]                  0         []

 xf (InputLayer)

 person_age_xf (InputLayer)  [(None, 1)]                  0         []

 person_income_xf (InputLay  [(None, 1)]                  0         []

 er)

 person_emp_length_xf (Inpu  [(None, 1)]                  0         []

 tLayer)

 loan_amnt_xf (InputLayer)   [(None, 1)]                  0         []

 loan_int_rate_xf (InputLay  [(None, 1)]                  0         []

 er)

 loan_percent_income_xf (In  [(None, 1)]                  0         []

 putLayer)

 cb_person_cred_hist_length  [(None, 1)]                  0         []

 _xf (InputLayer)

 tf.cast (TFOpLambda)        (None, 1)                    0         ['person_home_ownership_xf[0][

                                                                    0]']

 tf.cast_1 (TFOpLambda)      (None, 1)                    0         ['loan_intent_xf[0][0]']

 tf.cast_2 (TFOpLambda)      (None, 1)                    0         ['loan_grade_xf[0][0]']

 tf.cast_3 (TFOpLambda)      (None, 1)                    0         ['cb_person_default_on_file_xf

                                                                    [0][0]']

 concatenate (Concatenate)   (None, 11)                   0         ['person_age_xf[0][0]',

                                                                     'person_income_xf[0][0]',

                                                                     'person_emp_length_xf[0][0]',

                                                                     'loan_amnt_xf[0][0]',

                                                                     'loan_int_rate_xf[0][0]',

                                                                     'loan_percent_income_xf[0][0]

                                                                    ',

                                                                     'cb_person_cred_hist_length_x

                                                                    f[0][0]',

                                                                     'tf.cast[0][0]',

                                                                     'tf.cast_1[0][0]',

                                                                     'tf.cast_2[0][0]',

                                                                     'tf.cast_3[0][0]']

 dense (Dense)               (None, 128)                  1536      ['concatenate[0][0]']

 batch_normalization (Batch  (None, 128)                  512       ['dense[0][0]']

 Normalization)

 dropout (Dropout)           (None, 128)                  0         ['batch_normalization[0][0]']

 dense_1 (Dense)             (None, 64)                   8256      ['dropout[0][0]']

 batch_normalization_1 (Bat  (None, 64)                   256       ['dense_1[0][0]']

 chNormalization)

 dropout_1 (Dropout)         (None, 64)                   0         ['batch_normalization_1[0][0]'

                                                                    ]

 dense_2 (Dense)             (None, 32)                   2080      ['dropout_1[0][0]']

 batch_normalization_2 (Bat  (None, 32)                   128       ['dense_2[0][0]']

 chNormalization)

 dropout_2 (Dropout)         (None, 32)                   0         ['batch_normalization_2[0][0]'

                                                                    ]

 dense_3 (Dense)             (None, 1)                    33        ['dropout_2[0][0]']

==================================================================================================

Total params: 12801 (50.00 KB)

Trainable params: 12353 (48.25 KB)

Non-trainable params: 448 (1.75 KB)

__________________________________________________________________________________________________

Epoch 1/10

  1/500 [..............................] - ETA: 10:41 - loss: 1.1892 - binary_accuracy: 0.5938 - auc: 0.5165

 19/500 [>.............................] - ETA: 1s - loss: 1.1424 - binary_accuracy: 0.5066 - auc: 0.5025

 38/500 [=>............................] - ETA: 1s - loss: 1.0846 - binary_accuracy: 0.5119 - auc: 0.5111

 52/500 [==>...........................] - ETA: 1s - loss: 1.0674 - binary_accuracy: 0.5165 - auc: 0.5097

 71/500 [===>..........................] - ETA: 1s - loss: 1.0395 - binary_accuracy: 0.5257 - auc: 0.5179

 90/500 [====>.........................] - ETA: 1s - loss: 1.0237 - binary_accuracy: 0.5285 - auc: 0.5210

104/500 [=====>........................] - ETA: 1s - loss: 1.0075 - binary_accuracy: 0.5314 - auc: 0.5264

129/500 [======>.......................] - ETA: 1s - loss: 0.9896 - binary_accuracy: 0.5348 - auc: 0.5269

155/500 [========>.....................] - ETA: 1s - loss: 0.9761 - binary_accuracy: 0.5367 - auc: 0.5242

156/500 [========>.....................] - ETA: 1s - loss: 0.9748 - binary_accuracy: 0.5375 - auc: 0.5247

179/500 [=========>....................] - ETA: 1s - loss: 0.9612 - binary_accuracy: 0.5419 - auc: 0.5274

205/500 [===========>..................] - ETA: 0s - loss: 0.9449 - binary_accuracy: 0.5460 - auc: 0.5316

207/500 [===========>..................] - ETA: 1s - loss: 0.9441 - binary_accuracy: 0.5463 - auc: 0.5316

235/500 [=============>................] - ETA: 0s - loss: 0.9287 - binary_accuracy: 0.5502 - auc: 0.5368

259/500 [==============>...............] - ETA: 0s - loss: 0.9159 - binary_accuracy: 0.5556 - auc: 0.5407

285/500 [================>.............] - ETA: 0s - loss: 0.9029 - binary_accuracy: 0.5606 - auc: 0.5439

311/500 [=================>............] - ETA: 0s - loss: 0.8934 - binary_accuracy: 0.5628 - auc: 0.5451

339/500 [===================>..........] - ETA: 0s - loss: 0.8807 - binary_accuracy: 0.5682 - auc: 0.5491

362/500 [====================>.........] - ETA: 0s - loss: 0.8748 - binary_accuracy: 0.5685 - auc: 0.5490

387/500 [======================>.......] - ETA: 0s - loss: 0.8674 - binary_accuracy: 0.5703 - auc: 0.5501

414/500 [=======================>......] - ETA: 0s - loss: 0.8602 - binary_accuracy: 0.5714 - auc: 0.5504

442/500 [=========================>....] - ETA: 0s - loss: 0.8551 - binary_accuracy: 0.5722 - auc: 0.5503

466/500 [==========================>...] - ETA: 0s - loss: 0.8475 - binary_accuracy: 0.5754 - auc: 0.5522

492/500 [============================>.] - ETA: 0s - loss: 0.8428 - binary_accuracy: 0.5769 - auc: 0.5521

500/500 [==============================] - 3s 4ms/step - loss: 0.8409 - binary_accuracy: 0.5773 - auc: 0.5523 - val_loss: 0.6208 - val_binary_accuracy: 0.6670 - val_auc: 0.6426

Epoch 2/10

  1/500 [..............................] - ETA: 1s - loss: 0.6421 - binary_accuracy: 0.6875 - auc: 0.5905

 29/500 [>.............................] - ETA: 0s - loss: 0.7093 - binary_accuracy: 0.6212 - auc: 0.5668

 58/500 [==>...........................] - ETA: 0s - loss: 0.7164 - binary_accuracy: 0.6180 - auc: 0.5774

 86/500 [====>.........................] - ETA: 0s - loss: 0.7178 - binary_accuracy: 0.6134 - auc: 0.5685

114/500 [=====>........................] - ETA: 0s - loss: 0.7177 - binary_accuracy: 0.6120 - auc: 0.5677

141/500 [=======>......................] - ETA: 0s - loss: 0.7164 - binary_accuracy: 0.6120 - auc: 0.5695

171/500 [=========>....................] - ETA: 0s - loss: 0.7099 - binary_accuracy: 0.6173 - auc: 0.5739

198/500 [==========>...................] - ETA: 0s - loss: 0.7074 - binary_accuracy: 0.6168 - auc: 0.5758

222/500 [============>.................] - ETA: 0s - loss: 0.7051 - binary_accuracy: 0.6179 - auc: 0.5765

246/500 [=============>................] - ETA: 0s - loss: 0.7034 - binary_accuracy: 0.6200 - auc: 0.5769

271/500 [===============>..............] - ETA: 0s - loss: 0.6997 - binary_accuracy: 0.6214 - auc: 0.5795

288/500 [================>.............] - ETA: 0s - loss: 0.6976 - binary_accuracy: 0.6232 - auc: 0.5806

311/500 [=================>............] - ETA: 0s - loss: 0.6944 - binary_accuracy: 0.6251 - auc: 0.5837

335/500 [===================>..........] - ETA: 0s - loss: 0.6926 - binary_accuracy: 0.6252 - auc: 0.5843

357/500 [====================>.........] - ETA: 0s - loss: 0.6924 - binary_accuracy: 0.6251 - auc: 0.5835

384/500 [======================>.......] - ETA: 0s - loss: 0.6918 - binary_accuracy: 0.6260 - auc: 0.5829

409/500 [=======================>......] - ETA: 0s - loss: 0.6904 - binary_accuracy: 0.6260 - auc: 0.5837

431/500 [========================>.....] - ETA: 0s - loss: 0.6879 - binary_accuracy: 0.6267 - auc: 0.5859

454/500 [==========================>...] - ETA: 0s - loss: 0.6865 - binary_accuracy: 0.6269 - auc: 0.5868

478/500 [===========================>..] - ETA: 0s - loss: 0.6852 - binary_accuracy: 0.6279 - auc: 0.5876

500/500 [==============================] - 1s 3ms/step - loss: 0.6851 - binary_accuracy: 0.6274 - auc: 0.5868 - val_loss: 0.6106 - val_binary_accuracy: 0.6652 - val_auc: 0.6662

Epoch 3/10

  1/500 [..............................] - ETA: 1s - loss: 0.6870 - binary_accuracy: 0.6250 - auc: 0.5304

 25/500 [>.............................] - ETA: 0s - loss: 0.6616 - binary_accuracy: 0.6375 - auc: 0.6054

 51/500 [==>...........................] - ETA: 0s - loss: 0.6495 - binary_accuracy: 0.6437 - auc: 0.6106

 73/500 [===>..........................] - ETA: 0s - loss: 0.6490 - binary_accuracy: 0.6447 - auc: 0.6154

 97/500 [====>.........................] - ETA: 0s - loss: 0.6468 - binary_accuracy: 0.6467 - auc: 0.6169

119/500 [======>.......................] - ETA: 0s - loss: 0.6458 - binary_accuracy: 0.6485 - auc: 0.6167

141/500 [=======>......................] - ETA: 0s - loss: 0.6456 - binary_accuracy: 0.6471 - auc: 0.6150

166/500 [========>.....................] - ETA: 0s - loss: 0.6444 - binary_accuracy: 0.6485 - auc: 0.6159

193/500 [==========>...................] - ETA: 0s - loss: 0.6441 - binary_accuracy: 0.6486 - auc: 0.6167

217/500 [============>.................] - ETA: 0s - loss: 0.6413 - binary_accuracy: 0.6520 - auc: 0.6182

242/500 [=============>................] - ETA: 0s - loss: 0.6418 - binary_accuracy: 0.6514 - auc: 0.6192

267/500 [===============>..............] - ETA: 0s - loss: 0.6395 - binary_accuracy: 0.6536 - auc: 0.6213

292/500 [================>.............] - ETA: 0s - loss: 0.6398 - binary_accuracy: 0.6533 - auc: 0.6208

317/500 [==================>...........] - ETA: 0s - loss: 0.6394 - binary_accuracy: 0.6538 - auc: 0.6222

344/500 [===================>..........] - ETA: 0s - loss: 0.6386 - binary_accuracy: 0.6550 - auc: 0.6228

368/500 [=====================>........] - ETA: 0s - loss: 0.6383 - binary_accuracy: 0.6548 - auc: 0.6237

389/500 [======================>.......] - ETA: 0s - loss: 0.6370 - binary_accuracy: 0.6554 - auc: 0.6246

412/500 [=======================>......] - ETA: 0s - loss: 0.6365 - binary_accuracy: 0.6559 - auc: 0.6246

436/500 [=========================>....] - ETA: 0s - loss: 0.6359 - binary_accuracy: 0.6559 - auc: 0.6255

458/500 [==========================>...] - ETA: 0s - loss: 0.6354 - binary_accuracy: 0.6567 - auc: 0.6255

478/500 [===========================>..] - ETA: 0s - loss: 0.6352 - binary_accuracy: 0.6567 - auc: 0.6257

500/500 [==============================] - 2s 3ms/step - loss: 0.6350 - binary_accuracy: 0.6569 - auc: 0.6261 - val_loss: 0.6033 - val_binary_accuracy: 0.6702 - val_auc: 0.6800

Epoch 4/10

  1/500 [..............................] - ETA: 1s - loss: 0.5978 - binary_accuracy: 0.6875 - auc: 0.6978

 26/500 [>.............................] - ETA: 0s - loss: 0.6117 - binary_accuracy: 0.6755 - auc: 0.6575

 50/500 [==>...........................] - ETA: 0s - loss: 0.6173 - binary_accuracy: 0.6722 - auc: 0.6485

 74/500 [===>..........................] - ETA: 0s - loss: 0.6170 - binary_accuracy: 0.6725 - auc: 0.6496

102/500 [=====>........................] - ETA: 0s - loss: 0.6200 - binary_accuracy: 0.6673 - auc: 0.6465

132/500 [======>.......................] - ETA: 0s - loss: 0.6202 - binary_accuracy: 0.6670 - auc: 0.6480

161/500 [========>.....................] - ETA: 0s - loss: 0.6191 - binary_accuracy: 0.6657 - auc: 0.6480

189/500 [==========>...................] - ETA: 0s - loss: 0.6190 - binary_accuracy: 0.6641 - auc: 0.6489

217/500 [============>.................] - ETA: 0s - loss: 0.6177 - binary_accuracy: 0.6657 - auc: 0.6494

246/500 [=============>................] - ETA: 0s - loss: 0.6181 - binary_accuracy: 0.6632 - auc: 0.6493

276/500 [===============>..............] - ETA: 0s - loss: 0.6190 - binary_accuracy: 0.6629 - auc: 0.6493

303/500 [=================>............] - ETA: 0s - loss: 0.6168 - binary_accuracy: 0.6640 - auc: 0.6520

331/500 [==================>...........] - ETA: 0s - loss: 0.6154 - binary_accuracy: 0.6664 - auc: 0.6534

359/500 [====================>.........] - ETA: 0s - loss: 0.6166 - binary_accuracy: 0.6653 - auc: 0.6526

387/500 [======================>.......] - ETA: 0s - loss: 0.6162 - binary_accuracy: 0.6662 - auc: 0.6532

416/500 [=======================>......] - ETA: 0s - loss: 0.6160 - binary_accuracy: 0.6662 - auc: 0.6533

443/500 [=========================>....] - ETA: 0s - loss: 0.6149 - binary_accuracy: 0.6672 - auc: 0.6546

470/500 [===========================>..] - ETA: 0s - loss: 0.6152 - binary_accuracy: 0.6671 - auc: 0.6544

497/500 [============================>.] - ETA: 0s - loss: 0.6152 - binary_accuracy: 0.6673 - auc: 0.6544

500/500 [==============================] - 1s 3ms/step - loss: 0.6149 - binary_accuracy: 0.6677 - auc: 0.6546 - val_loss: 0.6017 - val_binary_accuracy: 0.6750 - val_auc: 0.6825

Epoch 5/10

  1/500 [..............................] - ETA: 2s - loss: 0.6443 - binary_accuracy: 0.6250 - auc: 0.6130

 30/500 [>.............................] - ETA: 0s - loss: 0.6162 - binary_accuracy: 0.6734 - auc: 0.6594

 56/500 [==>...........................] - ETA: 0s - loss: 0.6049 - binary_accuracy: 0.6814 - auc: 0.6718

 80/500 [===>..........................] - ETA: 0s - loss: 0.6030 - binary_accuracy: 0.6783 - auc: 0.6735

106/500 [=====>........................] - ETA: 0s - loss: 0.6048 - binary_accuracy: 0.6751 - auc: 0.6731

133/500 [======>.......................] - ETA: 0s - loss: 0.6058 - binary_accuracy: 0.6741 - auc: 0.6711

158/500 [========>.....................] - ETA: 0s - loss: 0.6050 - binary_accuracy: 0.6757 - auc: 0.6725

184/500 [==========>...................] - ETA: 0s - loss: 0.6047 - binary_accuracy: 0.6756 - auc: 0.6702

210/500 [===========>..................] - ETA: 0s - loss: 0.6052 - binary_accuracy: 0.6744 - auc: 0.6697

236/500 [=============>................] - ETA: 0s - loss: 0.6059 - binary_accuracy: 0.6723 - auc: 0.6713

264/500 [==============>...............] - ETA: 0s - loss: 0.6051 - binary_accuracy: 0.6735 - auc: 0.6722

290/500 [================>.............] - ETA: 0s - loss: 0.6053 - binary_accuracy: 0.6738 - auc: 0.6714

314/500 [=================>............] - ETA: 0s - loss: 0.6044 - binary_accuracy: 0.6742 - auc: 0.6727

339/500 [===================>..........] - ETA: 0s - loss: 0.6032 - binary_accuracy: 0.6747 - auc: 0.6748

366/500 [====================>.........] - ETA: 0s - loss: 0.6034 - binary_accuracy: 0.6740 - auc: 0.6744

392/500 [======================>.......] - ETA: 0s - loss: 0.6035 - binary_accuracy: 0.6740 - auc: 0.6741

419/500 [========================>.....] - ETA: 0s - loss: 0.6032 - binary_accuracy: 0.6736 - auc: 0.6744

445/500 [=========================>....] - ETA: 0s - loss: 0.6032 - binary_accuracy: 0.6731 - auc: 0.6742

471/500 [===========================>..] - ETA: 0s - loss: 0.6039 - binary_accuracy: 0.6728 - auc: 0.6734

499/500 [============================>.] - ETA: 0s - loss: 0.6037 - binary_accuracy: 0.6734 - auc: 0.6737

500/500 [==============================] - 1s 3ms/step - loss: 0.6037 - binary_accuracy: 0.6733 - auc: 0.6737 - val_loss: 0.5990 - val_binary_accuracy: 0.6714 - val_auc: 0.6863

Epoch 6/10

  1/500 [..............................] - ETA: 2s - loss: 0.5404 - binary_accuracy: 0.7500 - auc: 0.7906

 26/500 [>.............................] - ETA: 0s - loss: 0.6144 - binary_accuracy: 0.6695 - auc: 0.6637

 50/500 [==>...........................] - ETA: 0s - loss: 0.6064 - binary_accuracy: 0.6747 - auc: 0.6777

 75/500 [===>..........................] - ETA: 0s - loss: 0.6031 - binary_accuracy: 0.6787 - auc: 0.6785

 98/500 [====>.........................] - ETA: 0s - loss: 0.6055 - binary_accuracy: 0.6728 - auc: 0.6785

123/500 [======>.......................] - ETA: 0s - loss: 0.6040 - binary_accuracy: 0.6721 - auc: 0.6772

147/500 [=======>......................] - ETA: 0s - loss: 0.6013 - binary_accuracy: 0.6768 - auc: 0.6772

168/500 [=========>....................] - ETA: 0s - loss: 0.6013 - binary_accuracy: 0.6764 - auc: 0.6774

190/500 [==========>...................] - ETA: 0s - loss: 0.6024 - binary_accuracy: 0.6752 - auc: 0.6764

209/500 [===========>..................] - ETA: 2s - loss: 0.6020 - binary_accuracy: 0.6761 - auc: 0.6779

235/500 [=============>................] - ETA: 1s - loss: 0.6017 - binary_accuracy: 0.6757 - auc: 0.6770

261/500 [==============>...............] - ETA: 1s - loss: 0.6019 - binary_accuracy: 0.6750 - auc: 0.6777

288/500 [================>.............] - ETA: 1s - loss: 0.6010 - binary_accuracy: 0.6769 - auc: 0.6784

316/500 [=================>............] - ETA: 0s - loss: 0.5998 - binary_accuracy: 0.6789 - auc: 0.6798

345/500 [===================>..........] - ETA: 0s - loss: 0.6005 - binary_accuracy: 0.6786 - auc: 0.6792

371/500 [=====================>........] - ETA: 0s - loss: 0.6002 - binary_accuracy: 0.6791 - auc: 0.6796

397/500 [======================>.......] - ETA: 0s - loss: 0.6003 - binary_accuracy: 0.6781 - auc: 0.6794

423/500 [========================>.....] - ETA: 0s - loss: 0.6003 - binary_accuracy: 0.6776 - auc: 0.6794

451/500 [==========================>...] - ETA: 0s - loss: 0.6000 - binary_accuracy: 0.6777 - auc: 0.6800

475/500 [===========================>..] - ETA: 0s - loss: 0.6002 - binary_accuracy: 0.6772 - auc: 0.6806

500/500 [==============================] - 3s 5ms/step - loss: 0.5996 - binary_accuracy: 0.6778 - auc: 0.6808 - val_loss: 0.5976 - val_binary_accuracy: 0.6767 - val_auc: 0.6877

Epoch 7/10

  1/500 [..............................] - ETA: 2s - loss: 0.5423 - binary_accuracy: 0.7344 - auc: 0.7969

 24/500 [>.............................] - ETA: 1s - loss: 0.5906 - binary_accuracy: 0.6816 - auc: 0.6801

 46/500 [=>............................] - ETA: 1s - loss: 0.5975 - binary_accuracy: 0.6760 - auc: 0.6822

 68/500 [===>..........................] - ETA: 1s - loss: 0.5947 - binary_accuracy: 0.6776 - auc: 0.6852

 93/500 [====>.........................] - ETA: 0s - loss: 0.5937 - binary_accuracy: 0.6776 - auc: 0.6895

116/500 [=====>........................] - ETA: 0s - loss: 0.5957 - binary_accuracy: 0.6752 - auc: 0.6850

139/500 [=======>......................] - ETA: 0s - loss: 0.5961 - binary_accuracy: 0.6759 - auc: 0.6858

168/500 [=========>....................] - ETA: 0s - loss: 0.5972 - binary_accuracy: 0.6750 - auc: 0.6857

192/500 [==========>...................] - ETA: 0s - loss: 0.5947 - binary_accuracy: 0.6786 - auc: 0.6883

214/500 [===========>..................] - ETA: 0s - loss: 0.5958 - binary_accuracy: 0.6764 - auc: 0.6870

238/500 [=============>................] - ETA: 0s - loss: 0.5955 - binary_accuracy: 0.6776 - auc: 0.6874

265/500 [==============>...............] - ETA: 0s - loss: 0.5949 - binary_accuracy: 0.6790 - auc: 0.6895

290/500 [================>.............] - ETA: 0s - loss: 0.5955 - binary_accuracy: 0.6775 - auc: 0.6891

314/500 [=================>............] - ETA: 0s - loss: 0.5942 - binary_accuracy: 0.6784 - auc: 0.6904

339/500 [===================>..........] - ETA: 0s - loss: 0.5938 - binary_accuracy: 0.6792 - auc: 0.6912

363/500 [====================>.........] - ETA: 0s - loss: 0.5938 - binary_accuracy: 0.6797 - auc: 0.6912

392/500 [======================>.......] - ETA: 0s - loss: 0.5935 - binary_accuracy: 0.6799 - auc: 0.6917

417/500 [========================>.....] - ETA: 0s - loss: 0.5944 - binary_accuracy: 0.6793 - auc: 0.6902

439/500 [=========================>....] - ETA: 0s - loss: 0.5944 - binary_accuracy: 0.6790 - auc: 0.6907

464/500 [==========================>...] - ETA: 0s - loss: 0.5938 - binary_accuracy: 0.6795 - auc: 0.6913

490/500 [============================>.] - ETA: 0s - loss: 0.5939 - binary_accuracy: 0.6802 - auc: 0.6911

500/500 [==============================] - 2s 3ms/step - loss: 0.5938 - binary_accuracy: 0.6802 - auc: 0.6904 - val_loss: 0.5971 - val_binary_accuracy: 0.6825 - val_auc: 0.6915

Epoch 8/10

  1/500 [..............................] - ETA: 1s - loss: 0.5761 - binary_accuracy: 0.6562 - auc: 0.7677

 27/500 [>.............................] - ETA: 0s - loss: 0.5927 - binary_accuracy: 0.6811 - auc: 0.7130

 54/500 [==>...........................] - ETA: 0s - loss: 0.5865 - binary_accuracy: 0.6826 - auc: 0.7133

 81/500 [===>..........................] - ETA: 0s - loss: 0.5878 - binary_accuracy: 0.6869 - auc: 0.7057

111/500 [=====>........................] - ETA: 0s - loss: 0.5886 - binary_accuracy: 0.6867 - auc: 0.7041

138/500 [=======>......................] - ETA: 0s - loss: 0.5904 - binary_accuracy: 0.6842 - auc: 0.7024

164/500 [========>.....................] - ETA: 0s - loss: 0.5895 - binary_accuracy: 0.6855 - auc: 0.7020

192/500 [==========>...................] - ETA: 0s - loss: 0.5907 - binary_accuracy: 0.6830 - auc: 0.7022

219/500 [============>.................] - ETA: 0s - loss: 0.5890 - binary_accuracy: 0.6839 - auc: 0.7015

247/500 [=============>................] - ETA: 0s - loss: 0.5908 - binary_accuracy: 0.6829 - auc: 0.6999

272/500 [===============>..............] - ETA: 0s - loss: 0.5898 - binary_accuracy: 0.6833 - auc: 0.7000

299/500 [================>.............] - ETA: 0s - loss: 0.5912 - binary_accuracy: 0.6819 - auc: 0.6975

326/500 [==================>...........] - ETA: 0s - loss: 0.5900 - binary_accuracy: 0.6831 - auc: 0.6997

354/500 [====================>.........] - ETA: 0s - loss: 0.5901 - binary_accuracy: 0.6831 - auc: 0.6989

380/500 [=====================>........] - ETA: 0s - loss: 0.5900 - binary_accuracy: 0.6833 - auc: 0.6993

403/500 [=======================>......] - ETA: 0s - loss: 0.5902 - binary_accuracy: 0.6820 - auc: 0.6993

430/500 [========================>.....] - ETA: 0s - loss: 0.5899 - binary_accuracy: 0.6826 - auc: 0.6991

455/500 [==========================>...] - ETA: 0s - loss: 0.5897 - binary_accuracy: 0.6830 - auc: 0.6991

484/500 [============================>.] - ETA: 0s - loss: 0.5895 - binary_accuracy: 0.6827 - auc: 0.6991

500/500 [==============================] - 1s 3ms/step - loss: 0.5891 - binary_accuracy: 0.6831 - auc: 0.7000 - val_loss: 0.5962 - val_binary_accuracy: 0.6773 - val_auc: 0.6918

Epoch 9/10

  1/500 [..............................] - ETA: 2s - loss: 0.6673 - binary_accuracy: 0.7031 - auc: 0.6461

 25/500 [>.............................] - ETA: 0s - loss: 0.6030 - binary_accuracy: 0.6737 - auc: 0.6848

 50/500 [==>...........................] - ETA: 0s - loss: 0.5949 - binary_accuracy: 0.6781 - auc: 0.6909

 75/500 [===>..........................] - ETA: 0s - loss: 0.5945 - binary_accuracy: 0.6762 - auc: 0.6938

101/500 [=====>........................] - ETA: 0s - loss: 0.5904 - binary_accuracy: 0.6804 - auc: 0.6960

125/500 [======>.......................] - ETA: 0s - loss: 0.5931 - binary_accuracy: 0.6783 - auc: 0.6950

148/500 [=======>......................] - ETA: 0s - loss: 0.5913 - binary_accuracy: 0.6804 - auc: 0.6972

169/500 [=========>....................] - ETA: 0s - loss: 0.5916 - binary_accuracy: 0.6815 - auc: 0.6962

197/500 [==========>...................] - ETA: 0s - loss: 0.5906 - binary_accuracy: 0.6836 - auc: 0.6998

221/500 [============>.................] - ETA: 0s - loss: 0.5903 - binary_accuracy: 0.6845 - auc: 0.6991

245/500 [=============>................] - ETA: 0s - loss: 0.5902 - binary_accuracy: 0.6837 - auc: 0.6993

269/500 [===============>..............] - ETA: 0s - loss: 0.5900 - binary_accuracy: 0.6841 - auc: 0.6990

292/500 [================>.............] - ETA: 0s - loss: 0.5901 - binary_accuracy: 0.6838 - auc: 0.6995

313/500 [=================>............] - ETA: 0s - loss: 0.5903 - binary_accuracy: 0.6839 - auc: 0.6989

336/500 [===================>..........] - ETA: 0s - loss: 0.5901 - binary_accuracy: 0.6842 - auc: 0.6997

364/500 [====================>.........] - ETA: 0s - loss: 0.5891 - binary_accuracy: 0.6847 - auc: 0.7006

393/500 [======================>.......] - ETA: 0s - loss: 0.5900 - binary_accuracy: 0.6834 - auc: 0.6990

424/500 [========================>.....] - ETA: 0s - loss: 0.5895 - binary_accuracy: 0.6843 - auc: 0.7001

451/500 [==========================>...] - ETA: 0s - loss: 0.5896 - binary_accuracy: 0.6851 - auc: 0.6996

479/500 [===========================>..] - ETA: 0s - loss: 0.5895 - binary_accuracy: 0.6850 - auc: 0.7003

500/500 [==============================] - 1s 3ms/step - loss: 0.5889 - binary_accuracy: 0.6855 - auc: 0.7005 - val_loss: 0.5971 - val_binary_accuracy: 0.6770 - val_auc: 0.6908

Epoch 10/10

  1/500 [..............................] - ETA: 2s - loss: 0.5280 - binary_accuracy: 0.7188 - auc: 0.7174

 24/500 [>.............................] - ETA: 1s - loss: 0.5891 - binary_accuracy: 0.6777 - auc: 0.7076

 51/500 [==>...........................] - ETA: 0s - loss: 0.5901 - binary_accuracy: 0.6756 - auc: 0.7033

 74/500 [===>..........................] - ETA: 0s - loss: 0.5875 - binary_accuracy: 0.6780 - auc: 0.7057

100/500 [=====>........................] - ETA: 0s - loss: 0.5881 - binary_accuracy: 0.6791 - auc: 0.7026

124/500 [======>.......................] - ETA: 0s - loss: 0.5852 - binary_accuracy: 0.6816 - auc: 0.7061

149/500 [=======>......................] - ETA: 0s - loss: 0.5882 - binary_accuracy: 0.6805 - auc: 0.7023

174/500 [=========>....................] - ETA: 0s - loss: 0.5879 - binary_accuracy: 0.6820 - auc: 0.7018

198/500 [==========>...................] - ETA: 0s - loss: 0.5861 - binary_accuracy: 0.6828 - auc: 0.7055

221/500 [============>.................] - ETA: 0s - loss: 0.5857 - binary_accuracy: 0.6828 - auc: 0.7067

244/500 [=============>................] - ETA: 0s - loss: 0.5860 - binary_accuracy: 0.6836 - auc: 0.7053

272/500 [===============>..............] - ETA: 0s - loss: 0.5854 - binary_accuracy: 0.6852 - auc: 0.7055

295/500 [================>.............] - ETA: 0s - loss: 0.5856 - binary_accuracy: 0.6845 - auc: 0.7058

321/500 [==================>...........] - ETA: 0s - loss: 0.5860 - binary_accuracy: 0.6842 - auc: 0.7052

347/500 [===================>..........] - ETA: 0s - loss: 0.5858 - binary_accuracy: 0.6846 - auc: 0.7060

375/500 [=====================>........] - ETA: 0s - loss: 0.5860 - binary_accuracy: 0.6849 - auc: 0.7043

401/500 [=======================>......] - ETA: 0s - loss: 0.5857 - binary_accuracy: 0.6850 - auc: 0.7056

426/500 [========================>.....] - ETA: 0s - loss: 0.5855 - binary_accuracy: 0.6851 - auc: 0.7059

453/500 [==========================>...] - ETA: 0s - loss: 0.5854 - binary_accuracy: 0.6861 - auc: 0.7058

481/500 [===========================>..] - ETA: 0s - loss: 0.5844 - binary_accuracy: 0.6862 - auc: 0.7074

500/500 [==============================] - 1s 3ms/step - loss: 0.5845 - binary_accuracy: 0.6867 - auc: 0.7071 - val_loss: 0.5980 - val_binary_accuracy: 0.6752 - val_auc: 0.6933

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Trainer/model/6/Format-Serving/assets

INFO:tensorflow:Assets written to: /home/rzkycx/so/rzky0x-pipeline/Trainer/model/6/Format-Serving/assets

ExecutionResult(
    component_id: Trainer
    execution_id: 6
    outputs:
        model: OutputChannel(artifact_type=Model, producer_component_id=Trainer, output_key=model, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        model_run: OutputChannel(artifact_type=ModelRun, producer_component_id=Trainer, output_key=model_run, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

## 9. Komponen 7: Resolver

**Resolver** (LatestBlessedModelResolver) bertugas untuk mencari model terbaik yang telah di-"blessed" (lolos evaluasi) sebelumnya dari ML Metadata. Model ini akan digunakan sebagai baseline perbandingan oleh komponen Evaluator.

Pada run pertama, Resolver tidak akan menemukan model sebelumnya, sehingga Evaluator akan mengevaluasi model tanpa perbandingan baseline.

In [16]:
# Component 7: Resolver - Get latest blessed model for comparison
model_resolver = tfx.dsl.Resolver(
    strategy_class=tfx.dsl.experimental.LatestBlessedModelStrategy,
    model=tfx.dsl.Channel(type=tfx.types.standard_artifacts.Model),
    model_blessing=tfx.dsl.Channel(type=tfx.types.standard_artifacts.ModelBlessing)
)
context.run(model_resolver)

ExecutionResult(
    component_id: Resolver
    execution_id: 7
    outputs:
        model: OutputChannel(artifact_type=Model, producer_component_id=Resolver, output_key=model, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        model_blessing: OutputChannel(artifact_type=ModelBlessing, producer_component_id=Resolver, output_key=model_blessing, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

## 10. Komponen 8: Evaluator

**Evaluator** melakukan evaluasi mendalam terhadap model yang telah dilatih. Komponen ini:

- Menghitung metrik evaluasi (AUC, Binary Accuracy) pada seluruh dataset evaluasi
- Membandingkan performa model baru dengan model baseline (jika ada)
- Menentukan apakah model baru cukup baik untuk di-deploy ("blessing")

**Threshold yang ditetapkan:**
- AUC ≥ 0.7
- Binary Accuracy ≥ 0.7

Model hanya akan di-"blessed" jika memenuhi semua threshold di atas.

In [17]:
# Component 8: Evaluator - Evaluate model performance
eval_config = tfma.EvalConfig(
    model_specs=[
        tfma.ModelSpec(label_key='loan_status')
    ],
    slicing_specs=[
        tfma.SlicingSpec(),
    ],
    metrics_specs=[
        tfma.MetricsSpec(metrics=[
            tfma.MetricConfig(
                class_name='AUC',
                threshold=tfma.MetricThreshold(
                    value_threshold=tfma.GenericValueThreshold(
                        lower_bound={'value': 0.6}
                    ),
                    change_threshold=tfma.GenericChangeThreshold(
                        direction=tfma.MetricDirection.HIGHER_IS_BETTER,
                        absolute={'value': -1e-3}
                    )
                )
            ),
            tfma.MetricConfig(
                class_name='BinaryAccuracy',
                threshold=tfma.MetricThreshold(
                    value_threshold=tfma.GenericValueThreshold(
                        lower_bound={'value': 0.6}
                    )
                )
            ),
        ])
    ]
)

evaluator = tfx.components.Evaluator(
    examples=example_gen.outputs['examples'],
    model=trainer.outputs['model'],
    baseline_model=model_resolver.outputs['model'],
    eval_config=eval_config
)
context.run(evaluator)

WARNING:tensorflow:From /home/rzkycx/so/mlops-env/lib/python3.9/site-packages/tensorflow_model_analysis/writers/metrics_plots_and_validations_writer.py:112: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and:
`tf.data.TFRecordDataset(path)`

WARNING:tensorflow:From /home/rzkycx/so/mlops-env/lib/python3.9/site-packages/tensorflow_model_analysis/writers/metrics_plots_and_validations_writer.py:112: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and:
`tf.data.TFRecordDataset(path)`

ExecutionResult(
    component_id: Evaluator
    execution_id: 8
    outputs:
        evaluation: OutputChannel(artifact_type=ModelEvaluation, producer_component_id=Evaluator, output_key=evaluation, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False)
        blessing: OutputChannel(artifact_type=ModelBlessing, producer_component_id=Evaluator, output_key=blessing, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [18]:
# Check if model is blessed
evaluation_result = evaluator.outputs['blessing'].get()[0]
print(f'Model blessing result: {evaluation_result}')

Model blessing result: Artifact(artifact: id: 16
name: "blessing:2026-06-12T21:55:39.205484"
type_id: 30
uri: "/home/rzkycx/so/rzky0x-pipeline/Evaluator/blessing/8"
custom_properties {
  key: "tfx_version"
  value {
    string_value: "1.15.0"
  }
}
custom_properties {
  key: "producer_component"
  value {
    string_value: "Evaluator"
  }
}
custom_properties {
  key: "name"
  value {
    string_value: "blessing:2026-06-12T21:55:39.205484"
  }
}
custom_properties {
  key: "current_model"
  value {
    string_value: "/home/rzkycx/so/rzky0x-pipeline/Trainer/model/6"
  }
}
custom_properties {
  key: "current_model_id"
  value {
    int_value: 13
  }
}
custom_properties {
  key: "blessed"
  value {
    int_value: 1
  }
}
state: LIVE
, artifact_type: id: 30
name: "ModelBlessing"
)

## 11. Komponen 9: Pusher

**Pusher** adalah komponen terakhir dalam pipeline. Komponen ini bertugas untuk:
- Memeriksa apakah model telah di-"blessed" oleh Evaluator
- Jika model lolos evaluasi, menyalin model ke direktori serving (`serving_model/`)
- Model yang di-push dapat langsung digunakan oleh TensorFlow Serving

Model akan disimpan di: `rzky0x-pipeline/serving_model/credit-risk-model/`

In [19]:
# Component 9: Pusher - Push blessed model to serving directory
pusher = tfx.components.Pusher(
    model=trainer.outputs['model'],
    model_blessing=evaluator.outputs['blessing'],
    push_destination=tfx.proto.PushDestination(
        filesystem=tfx.proto.PushDestination.Filesystem(
            base_directory=SERVING_MODEL_DIR
        )
    )
)
context.run(pusher)

ExecutionResult(
    component_id: Pusher
    execution_id: 9
    outputs:
        pushed_model: OutputChannel(artifact_type=PushedModel, producer_component_id=Pusher, output_key=pushed_model, additional_properties={}, additional_custom_properties={}, _input_trigger=None, _is_async=False))

In [20]:
# Check pusher output
pusher_artifact = pusher.outputs['pushed_model'].get()[0]
print(f'Pushed model URI: {pusher_artifact.uri}')
print(f'Pushed model version: {pusher_artifact.get_int_custom_property("pushed_version")}')

Pushed model URI: /home/rzkycx/so/rzky0x-pipeline/Pusher/pushed_model/9
Pushed model version: 0

## 12. Verifikasi Model

Memverifikasi bahwa model telah berhasil disimpan dan dapat dimuat untuk serving.

In [21]:
# Verify serving model directory
import glob

serving_models = glob.glob(os.path.join(SERVING_MODEL_DIR, '*'))
print(f'Serving models found: {serving_models}')

if serving_models:
    latest_model = max(serving_models)
    print(f'Latest serving model: {latest_model}')
    
    # List model contents
    for root, dirs, files in os.walk(latest_model):
        level = root.replace(latest_model, '').count(os.sep)
        indent = ' ' * 2 * level
        print(f'{indent}{os.path.basename(root)}/')
        sub_indent = ' ' * 2 * (level + 1)
        for file in files:
            print(f'{sub_indent}{file}')

Serving models found: ['/home/rzkycx/so/rzky0x-pipeline/serving_model/1781272548']
Latest serving model: /home/rzkycx/so/rzky0x-pipeline/serving_model/1781272548
1781272548/
  saved_model.pb
  keras_metadata.pb
  fingerprint.pb
  assets/
    vocab_compute_and_apply_vocabulary_2_vocabulary
    vocab_compute_and_apply_vocabulary_1_vocabulary
    vocab_compute_and_apply_vocabulary_3_vocabulary
    vocab_compute_and_apply_vocabulary_vocabulary
  variables/
    variables.data-00000-of-00001
    variables.index

## 13. Pipeline Summary

Pipeline telah berhasil dijalankan dengan semua 9 komponen TFX:

| No | Komponen | Status | Deskripsi |
|---|---|---|---|
| 1 | ExampleGen | ✅ | Data CSV berhasil di-ingest dan di-split |
| 2 | StatisticsGen | ✅ | Statistik deskriptif telah dihasilkan |
| 3 | SchemaGen | ✅ | Schema data berhasil diinferensikan |
| 4 | ExampleValidator | ✅ | Data tervalidasi terhadap schema |
| 5 | Transform | ✅ | Feature engineering selesai |
| 6 | Trainer | ✅ | Model DNN berhasil dilatih |
| 7 | Resolver | ✅ | Baseline model resolved |
| 8 | Evaluator | ✅ | Model dievaluasi dan di-blessed |
| 9 | Pusher | ✅ | Model di-push ke serving directory |

**Orchestrator:** Apache Beam (DirectRunner)  
**Pipeline Output:** `rzky0x-pipeline/`  
**Serving Model:** `rzky0x-pipeline/serving_model/`